### ISSUE TITLE
验证集结果全为-1 ？

### ISSUE THREAD

**Issue by zhijiejia** [CarryHJR/LogDet#14]
大佬又遇到这种情况吗？ 我跑了3epoch了，还都是-1，不知道这是咋回事啊。。

![image](https://user-images.githubusercontent.com/43838913/163701782-2a03c2b3-14c2-4af3-8897-d1f2e152bd89.png)

**Comment by CarryHJR** [comment]
看起来是你设定的val json有问题

**Comment by zhijiejia** [comment]
我就是直接指向的官方给的数据集啊，没动啊。。

**Comment by zhijiejia** [comment]
哦哦，原来那个test.zip 解压后是val文件夹，。。。，我以为官方分好了验证集了呢，原来是没有分

**Comment by CarryHJR** [comment]
我配置里面的train val 使用的是 https://github.com/CarryHJR/LogDet/tree/master/ContestStage1/data，在readme里面都有说明，请仔细阅读
