### ISSUE TITLE
大佬你好，我在mmedetection上使用比赛数据用您的基线模型时会报如下错误：TypeError: function takes exactly 5 arguments (1 given)，但在logdet-mini可以正常运行，对比发现好像是json文件的问题，不知道到底错哪了

### ISSUE THREAD

**Issue by gkgo** [CarryHJR/LogDet#16]
报错信息：
![屏幕截图 2022-04-19 173908](https://user-images.githubusercontent.com/91817417/163976565-532958b7-8bfa-4b06-92bc-836b766d1369.png)
正式比赛的json文件
![屏幕截图 2022-04-19 173940](https://user-images.githubusercontent.com/91817417/163976715-f0ef3e29-4ebd-4508-a769-7af7d3cc3c24.png)
logdet-mini的json文件
![屏幕截图 2022-04-19 174521](https://user-images.githubusercontent.com/91817417/163976900-19f4339b-990b-430e-b4e4-b53d53461890.png)
自己改的configs文件运行也是这个错误，但在其他数据集上可以正常运行，您可以帮忙看看吗，好久都没解决

**Comment by CarryHJR** [comment]
看起来是你的config里面的dataset 相关的error

**Comment by gkgo** [comment]
谢谢您，我仔细看了一下还是没发现哪里错了，但是我在kaggle上跑可以运行，可能是我环境有点问题

**Comment by CarryHJR** [comment]
pip install -U pycocotools==2.0.2

**Comment by CarryHJR** [comment]
export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
