### ISSUE TITLE
关于训练尺度的问题

### ISSUE THREAD

**Issue by WhereKey** [CarryHJR/LogDet#22]
你好，我在你的baseline上面改了一些东西，目前分数0.62+。 有一大部分是大尺度训练尺度带来的功劳，但是当我把尺度变得更大 img_scale=[(3200, 1750), (3200, 2134)], 发现分数反而下降了0.01，这是我很疑惑的地方。是否是resize的时候导致大量图片失真了，还是我应该加大数据增强？

**Comment by CarryHJR** [comment]
推断不出来，建议先在val上看看是不是某些特定类别掉点再讨论

**Comment by WhereKey** [comment]
> 推断不出来，建议先在val上看看是不是某些特定类别掉点再讨论

非常感谢你的建议，这确实是我忽略的一个关键点

**Comment by Hzj199** [comment]
> > 推断不出来，建议先在val上看看是不是某些特定类别掉点再讨论
> 
> 非常感谢你的建议，这确实是我忽略的一个关键点

请问您发现的最大有效分辨率是 1600 左右吗？
