### ISSUE TITLE
报错：TypeError: CascadeRCNN: SwinTransformer: __init__() got an unexpected keyword argument 'embed_dim'

### ISSUE THREAD

**Issue by RXZ-BUPT** [CarryHJR/LogDet#8]
配置好config后，在运行train.py时报错，请问有大佬遇到过这个问题吗？怎么解决呢？

**Comment by RXZ-BUPT** [comment]
我用得就是最新版本的mmdet,更改之后这部分不会报错了，但是又有新的错误：CascadeRCNN: CascadeRoIHead: SingleRoIExtractor: __init__() got an unexpected keyword argument 'gc_context'，也是这种类型的问题，为什么会这样呢？

**Comment by CarryHJR** [comment]
你可以去掉这个参数，或者 [refer](https://github.com/CarryHJR/LogDet/issues/5)

**Comment by RXZ-BUPT** [comment]
你好，我更改了这部分之后，又有新的报错：KeyError: 'DistOptimizerHook is not in the hook registry'请问一下这是什么情况呢？

**Comment by CarryHJR** [comment]
我用的是 来自 https://github.com/SwinTransformer/Swin-Transformer-Object-Detection 的mmdetection 版本，里面有个mmcv_custom

**Comment by weison10** [comment]
> 

大佬，mmcv_custom然后呢，是直接cope过去吗

**Comment by zebrazjx** [comment]
请问这个问题怎么解决的，我也是卡在这里了

**Comment by Zjy0401** [comment]
`mmdet/utils/__init__.py` 中进行注册，修改为：
`__all__ = ['get_root_logger', 'collect_env', 'DistOptimizerHook']`

**Comment by Rongyimin-z** [comment]
> 

引用的的DistOptimizerHook是来在哪里的
